# Staging Environment Patches
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    prometheus:
      prometheusSpec:
        retention: 15d
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 1Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 20Gi
    grafana:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 300m
          memory: 300Mi
