# Prometheus Operator HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "55.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        retention: 10d
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 1Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: managed-premium
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: managed-premium
              resources:
                requests:
                  storage: 5Gi
    nodeExporter:
      enabled: true
    kubelet:
      enabled: true
      serviceMonitor:
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance
