# Flux Kustomization for Development Environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./namespaces
  - ./infrastructure
  - ./apps

patchesStrategicMerge:
  - ./patches/common.yaml
