name: Fetch Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Azure resource group name'
        required: true
        default: ''

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Fetch resources from resource group
      run: |
        echo "Fetching resources in RG: ${{ github.event.inputs.resource_group }}"
        az resource list \
          --resource-group ${{ github.event.inputs.resource_group }} \
          --output table
